### ISSUE TITLE
Pagination is not showing up 

### ISSUE THREAD

**Issue by agneszan** [getButterfly/imagepress#75]
Hello,Can you tell me how can I show the pagination under the images like in the [demo](https://getbutterfly.com/photo-gallery/).

Here is the [site](http://www.notchabovephotoclub.com/press-galleries/).
Thank You.

**Comment by wolffe** [comment]
The pagination is automatic. There's nothing you need to do.

Do you have a limit on images? How does your shortcode look like?

**Comment by agneszan** [comment]
The shortcode is [imagepress-loop filters="yes" count="6"] .

**Comment by wolffe** [comment]
Remove the `count="6"` and it will work.

**Comment by agneszan** [comment]
Done , still not working

**Comment by wolffe** [comment]
Add more images and it will work. Or set a lower number of images from **ImagePress Settings** -> **Configurator** -> **Images per page**.

**Comment by agneszan** [comment]
Im blind , i had to change the limit per page. Worked thank you .

**Comment by wolffe** [comment]
You are welcome!
